In [ ]:
import numpy as np
import pandas as pd
import plotly.express as px

Standard template by Clinton Boyda modelled from AMII labs and https://www.v7labs.com/blog/data-preprocessing-guide

In [ ]:
# Connect to Dataset
filename = "https://raw.githubusercontent.com/cboyda/MachineLearning/main/AB_NYC_2019.csv"

df = pd.read_csv(filename)

Let's start cleaning the data...

<h2>Data Preprocessing: Best practices</h2><p>Here's a short recap of everything we've learnt about data preprocessing:</p><ul role="list"><li>The first step in Data Preprocessing is to understand your data. Just looking at <a href="https://www.v7labs.com/blog/best-free-datasets-for-machine-learning">your dataset</a> can give you an intuition of what things you need to focus on.</li><li>Use statistical methods or pre-built libraries that help you visualize the dataset and give a clear image of how your data looks in terms of class distribution.&nbsp;</li><li>Summarize your data in terms of the number of duplicates, missing values, and outliers present in the data.</li><li>Drop the fields you think have no use for the modeling or are closely related to other attributes. Dimensionality reduction is one of the very important aspects of Data Preprocessing.</li><li>Do some feature engineering and figure out which attributes contribute most towards model training.</li>

Main steps include:


0.   Review Data Visually
1.   Data Profiling (data quality)
2.   Data Cleaning (fixing data)
3.   Data Monitoring (continously maintaining data integrity)

# 0.0 Look at Data

0.1 View data

In [ ]:
df.shape

(48895, 16)

In [ ]:
print("Number of Examples/Rows:", len(df))
print("Number Features/Columns:", len(df.columns)-1 , "plus 1 label column.")
print("Total Features/Columns =", len(df.columns))

Number of Examples/Rows: 48895
Number Features/Columns: 15 plus 1 label column.
Total Features/Columns = 16

In [ ]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [ ]:
df.tail()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
48890,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,2,9
48891,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,2,36
48892,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,NaN,1,27
48893,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,6,2
48894,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,1,23

In [ ]:
# are the numbers proper integer or float datatypes ?
# do we have convert objects to integers?
df.dtypes

id                                  int64
name                               object
host_id                             int64
host_name                          object
neighbourhood_group                object
neighbourhood                      object
latitude                          float64
longitude                         float64
room_type                          object
price                               int64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object

In [ ]:
# set universal variables
numeric_data = df.select_dtypes(include=[np.number])
categorical_data = df.select_dtypes(exclude=[np.number])
print("NUMERICAL Data Columns:")
print(numeric_data.count())
print("\n")
print(numeric_data.dtypes)
print("\n")
print("CATEGORICAL Data Columns:")
print(categorical_data.count())
print("\n")
print(categorical_data.dtypes)

NUMERICAL Data Columns:
id                                48895
host_id                           48895
latitude                          48895
longitude                         48895
price                             48895
minimum_nights                    48895
number_of_reviews                 48895
reviews_per_month                 38843
calculated_host_listings_count    48895
availability_365                  48895
dtype: int64


id                                  int64
host_id                             int64
latitude                          float64
longitude                         float64
price                               int64
minimum_nights                      int64
number_of_reviews                   int64
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object


CATEGORICAL Data Columns:
name                   48879
host_name              48874
neighbourhood_group    48895
neighbourhood          48895
room_type              48895
last_review            38843
dtype: int64


name                   object
host_name              object
neighbourhood_group    object
neighbourhood          object
room_type              object
last_review            object
dtype: object

In [ ]:
df.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,4.889500e+04,4.889500e+04,48895.000000,48895.000000,48895.000000,48895.000000,48895.000000,38843.000000,48895.000000,48895.000000
mean,1.901714e+07,6.762001e+07,40.728949,-73.952170,152.720687,7.029962,23.274466,1.373221,7.143982,112.781327
std,1.098311e+07,7.861097e+07,0.054530,0.046157,240.154170,20.510550,44.550582,1.680442,32.952519,131.622289
min,2.539000e+03,2.438000e+03,40.499790,-74.244420,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000
25%,9.471945e+06,7.822033e+06,40.690100,-73.983070,69.000000,1.000000,1.000000,0.190000,1.000000,0.000000
50%,1.967728e+07,3.079382e+07,40.723070,-73.955680,106.000000,3.000000,5.000000,0.720000,1.000000,45.000000
75%,2.915218e+07,1.074344e+08,40.763115,-73.936275,175.000000,5.000000,24.000000,2.020000,2.000000,227.000000
max,3.648724e+07,2.743213e+08,40.913060,-73.712990,10000.000000,1250.000000,629.000000,58.500000,327.000000,365.000000

# 1.0 DATA PROFILING
Exploring the data quality issues.

1.1 Test for Duplicates

In [ ]:
# Any duplicates exist?
duplicate_rows = df.duplicated()
display(duplicate_rows.any())

False

In [ ]:
# count number of duplicates
duplicate_rows.sum()

0

1.2 Test for Nan, Null, Blanks or "?" symbols.


*   Detect missing values with isnull() AND isna()
*   Count numbers missing for each ROW 
`df.isnull().sum(axis=1))`
*   Count numbers missing for each COLUMN 
`df.isnull().sum())`

In [ ]:
# count number of NaN values anywhere in dataframe
count_nan_in_df = df.isna().sum().sum()
print ('Count of NaN: ' + str(count_nan_in_df))

Count of NaN: 20141

In [ ]:
#do null values exist?
result = df.isnull().sum().sum()
result > 0

True

In [ ]:
# count number of null values for each column
df.isnull().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [ ]:
# percentage of null values for each column
100*(df.isnull().sum())/len(df)

id                                 0.000000
name                               0.032723
host_id                            0.000000
host_name                          0.042949
neighbourhood_group                0.000000
neighbourhood                      0.000000
latitude                           0.000000
longitude                          0.000000
room_type                          0.000000
price                              0.000000
minimum_nights                     0.000000
number_of_reviews                  0.000000
last_review                       20.558339
reviews_per_month                 20.558339
calculated_host_listings_count     0.000000
availability_365                   0.000000
dtype: float64

<img src='https://assets-global.website-files.com/5d7b77b063a9066d83e1209c/6137498cffab3f77704b5c72_missing-noisy-incosistent-data.png' align="center" width="80%">

# Data Cleaning

## Missing Values
Why is data missing?
* MCAR: Missing Completely At Random 
    * while convenient and having fewer consequences this assumption is often unrealistic https://stefvanbuuren.name/fimd/sec-MCAR.html 
* MNAR: Missing Not At Random - Difficult to deal with
    * solution strategies often require finding causes
* MAR: Missing At Random - We can handle

Strategies for dealing with missing values
* The best strategy by a large margin (if you can do this, do this!): Recover lost data
* Listwise deletion (remove incomplete rows)
* Dropping the feature (remove entire columns)
* Imputing (filling in) values (risk biasing the data)

There are different strategies for imputing missing values. From simple to complex:
* Imputation with a constant with a fixed value
* Imputation with a constant with a value dependent on existing feature values
* Imputation with the value of a function dependent on other feature values
* Imputation with another ML model
* Making educated guesses!!! doing imputation will cause a net loss in the useful information content of our data, if done naively.
    * for categorical = just use ‘missing’
        * solved with supervised learning
    * for numeric = can add new column to designate that imputation was used (boolean)
        * solved with regression methods

Time-stamped missing information?

Last Observation Carried Forward
(LOCF)
* In this strategy, a missing value in a feature is replaced by the last (according to the sequence of instances) instance whose value for that feature was not missing. The caveat is we can't impute values for missing values that happen at the beginning of the sequence of instances.
or

Next Observation Carried Backward
(NOCB)
* As the name implies, this strategy is the reverse of LOCF: a missing value in a feature is replaced by the next (according to the sequence of instances) instance whose value for that feature was not missing. The caveat with this one is we can't impute values for missing values that happen at the end of the sequence of instances.

In [ ]:
# BEFORE dropping data consider % of its value
# calculate percentage of values over our extreme, if under 5% consider dropping

#display ('Availability_365 percentage over extreme:')
#(df.loc[df.availability_365 == 0, 'availability_365'].count() / df.availability_365.count()) * 100

## Noisy Data

## Removing Outliers
How to detect outliers?
* Use a visualization such as a box plot, a violin plot, a histogram or a scatterplot visualization;
* Calculate z-scores for feature values and compare them to the standard deviation of that feature (more on this when we talk about normalization);
* Use unsupervised learning, e.g., clustering algorithms. Anomaly detection is one the use cases of unsupervised learning and outliers are a kind of anomaly. Methods such as density-based clustering algorithms such as DBSCAN or Ordering points to identify the clustering structure (OPTICS) can be used to effectively identify outliers. These methods lie outside the scope of this course and we will not be talking about them but it is important for you to know about their existence;
* Use a binary classifier to divide the points into a "normal" and a "non-normal" class.
Cause?
* bad data collection (don’t want)
* or because of phenomena we should be aware of? (want to keep)

In [ ]:
# confirm standard deviation for price is too large = needs to drop extreme values
df.describe(include='all').loc['std']

id                                 10983108.38561
name                                          NaN
host_id                           78610967.032667
host_name                                     NaN
neighbourhood_group                           NaN
neighbourhood                                 NaN
latitude                                  0.05453
longitude                                0.046157
room_type                                     NaN
price                                   240.15417
minimum_nights                           20.51055
number_of_reviews                       44.550582
last_review                                   NaN
reviews_per_month                        1.680442
calculated_host_listings_count          32.952519
availability_365                       131.622289
Name: std, dtype: object

In [ ]:
# check whisker/box for outliers
for column in df.columns:
  fig = px.histogram(df, x=column, marginal="box")
  fig.show()

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
# lookup in extreme_values UPPER/LOWER FENCE values
def get_upperfence(name=''):
  for i in range(len(extreme_values)):
    if extreme_values[i][0] == name:
      return extreme_values[i][2]
    else:
      continue

def get_lowerfence(name=''):
  for i in range(len(extreme_values)):
    if extreme_values[i][0] == name:
      return extreme_values[i][1]
    else:
      continue

In [ ]:
# what precisely are our upper and lower whisker box amounts
# this will help flush out our outliers or too large of standard deviations
extreme_values = []
for column in numeric_data.columns:
  # Select the first quantile
  q1 = df[column].quantile(0.25)

  # Select the third quantile
  q3 = df[column].quantile(0.75)

  max = df[column].quantile(1)

  # Create a mask inbetween q1 & q3
  IQR = q3 - q1

  # Filtering the initial dataframe with a mask
  #filtered = df.query('(@q1 - 1.5 * @IQR) <= [column] <= (@q3 + 1.5 * @IQR)')
  # Filtering Values between Q1-1.5IQR and Q3+1.5IQR  

  #maximum outliers
  bottom_fence = 0 if (q1 - 1.5 * IQR) < 0 else q1 - 1.5 * IQR
  upper_fence = max if (q3 + 1.5 * IQR) > max else (q3 + 1.5 * IQR)
  #display(column, bottom_fence, upper_fence)
  extreme_values.append([column, bottom_fence, upper_fence])

In [ ]:
extreme_values

[['id', 0, 36487245.0],
 ['host_id', 0, 256853008.0],
 ['latitude', 40.580577500000004, 40.872637499999996],
 ['longitude', 0, -73.86608249999999],
 ['price', 0, 334.0],
 ['minimum_nights', 0, 11.0],
 ['number_of_reviews', 0, 58.5],
 ['reviews_per_month', 0, 4.765000000000001],
 ['calculated_host_listings_count', 0, 3.5],
 ['availability_365', 0, 365.0]]

## Correlate Columns to Keep

In [ ]:
#sample from  https://stackoverflow.com/questions/66572672/correlation-heatmap-in-plotly
# Correlation
df_corr = df.corr().round(1)  
# Mask to matrix
mask = np.zeros_like(df_corr, dtype=bool)
mask[np.triu_indices_from(mask)] = True
# Viz
df_corr_viz = df_corr.mask(mask).dropna(how='all').dropna(how='all')
# colour variable https://plotly.com/python/colorscales/
fig = px.imshow(df_corr_viz, text_auto=True, color_continuous_scale=[(0.00, "black"),   (0.33, "black"),
                                                     (0.33, "white"), (0.66, "white"),
                                                     (0.66, "blue"),  (1.00, "blue")])
fig.show()

CONSIDER: Low or no correlation features should be dropped.

... now check 2.2 group 2.3 for more steps